### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by qq283436889** [shixiaoquan/react-native-webview-fixed-android#1]

**Comment by qq283436889** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.webkit.ValueCallback.onReceiveValue(java.lang.Object)' on a null object reference
        at com.shixiaoquan.webview.RNWebViewManager.callback(RNWebViewManager.java:604)
        at com.shixiaoquan.webview.PickerActivityEventListener.onActivityResult(PickerActivityEventListener.java:25)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:253)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:721)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:149)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
        at android.app.Activity.dispatchActivityResult(Activity.java:6984)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4235)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4282) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6326) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by qq283436889** [comment]
选择图片跟拍照都是提示
'void android.webkit.ValueCallback.onReceiveValue(java.lang.Object)' on a null object reference
